# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 18:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='This will appear as the main project title', max_length=200, verbose_name='project title')),
                ('brief_description', models.TextField(help_text='Very short descrition. Will appear on project listing.', verbose_name='brief description')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 6, 25, 18, 48, 48, 125808, tzinfo=utc), verbose_name='date published')),
                ('thumbnail', models.ImageField(upload_to='projects/thumbnail/')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
    ]
