# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170625_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='brief_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, help_text='Desciption of the project (not actually explanation)', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.TextField(default='details', help_text='Full explanation of the project)', verbose_name='details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.CharField(default='summary', help_text='Very short descrition. Will appear on project listing.', max_length=140, verbose_name='brief description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='last update date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Title used for listing', max_length=60, verbose_name='title'),
        ),
    ]
