# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170626_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildSteep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Explanation of one individual step on the elavoration fo the project', verbose_name='steep content')),
                ('number', models.IntegerField(verbose_name='position on steep list')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name_plural': 'projects',
                'verbose_name': 'project',
            },
        ),
    ]
