# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_buildsteep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildsteep',
            options={'verbose_name': 'project steep', 'verbose_name_plural': 'project steeps'},
        ),
    ]
