# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170628_1531'),
        ('projects', '0005_auto_20170627_1054'),
    ]

    operations = [
    ]
