# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_merge_20170629_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('university', models.CharField(help_text='Very short descrition. Will appear on project listing.', max_length=140, verbose_name='brief description')),
                ('website', models.CharField(blank=True, max_length=256)),
                ('facebook', models.CharField(blank=True, max_length=128)),
                ('twitter', models.CharField(blank=True, max_length=128)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='last update date')),
                ('logo', models.ImageField(upload_to='projects/organization/')),
            ],
            options={
                'verbose_name_plural': 'organizations',
                'verbose_name': 'organization',
            },
        ),
        migrations.AlterField(
            model_name='buildsteep',
            name='content',
            field=tinymce.models.HTMLField(help_text='Explanation of one individual step on the elavoration fo the project', verbose_name='steep content'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(help_text='Desciption of the project (not actually explanation)', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='details',
            field=tinymce.models.HTMLField(help_text='Full explanation of the project)', verbose_name='details'),
        ),
    ]
