# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20170629_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='university',
            field=models.CharField(max_length=64),
        ),
    ]
