# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20170629_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ieee',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
