# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_organization_ieee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('brief', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('COD', 'code'), ('WEB', 'website'), ('DOC', 'document'), ('OTH', 'other')], max_length=3)),
                ('url', models.CharField(max_length=512, verbose_name='url')),
            ],
            options={
                'verbose_name_plural': 'folile resources',
                'verbose_name': 'file resource',
            },
        ),
        migrations.CreateModel(
            name='FileResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('brief', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('IMG', 'image'), ('COD', 'code'), ('DOC', 'document'), ('OTH', 'other')], max_length=3)),
                ('logo', models.FilePathField()),
            ],
            options={
                'verbose_name_plural': 'folile resources',
                'verbose_name': 'file resource',
            },
        ),
    ]
