# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_externalresource_fileresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildsteep',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
