# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 09:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_buildsteep_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='title')),
                ('content', tinymce.models.HTMLField(verbose_name='blog entry content')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 7, 2, 9, 48, 25, 366240, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'resources',
                'verbose_name': 'resource',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='name')),
                ('brief', models.CharField(blank=True, max_length=128)),
                ('type', models.CharField(choices=[('IMG', 'image'), ('COD', 'code'), ('DOC', 'document'), ('FIL', 'other'), ('WEB', 'website')], max_length=3)),
                ('file', models.FilePathField()),
                ('special_type', models.CharField(blank=True, max_length=32)),
                ('url', models.CharField(max_length=512, verbose_name='url')),
                ('blogEntry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.BlogEntry')),
            ],
            options={
                'verbose_name_plural': 'resources',
                'verbose_name': 'resource',
            },
        ),
        migrations.DeleteModel(
            name='ExternalResource',
        ),
        migrations.DeleteModel(
            name='FileResource',
        ),
        migrations.RemoveField(
            model_name='buildsteep',
            name='id',
        ),
        migrations.AlterField(
            model_name='buildsteep',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='position on steep list'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='projects/organization/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='university',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='project',
            name='details',
            field=tinymce.models.HTMLField(blank=True, help_text='Full explanation of the project)', verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='projects/thumbnail/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='buildSteep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.BuildSteep'),
        ),
        migrations.AddField(
            model_name='resource',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='blogentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
