# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 09:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20170702_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildsteep',
            name='number',
        ),
        migrations.AddField(
            model_name='buildsteep',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildsteep',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 2, 9, 51, 36, 175272, tzinfo=utc)),
        ),
    ]
