# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20170702_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogentry',
            options={'verbose_name': 'blog entry', 'verbose_name_plural': 'blog entries'},
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='facebook',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='projects/organization/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='twitter',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='university',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='details',
            field=tinymce.models.HTMLField(blank=True, help_text='Full explanation of the project)', null=True, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='projects/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='brief',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='special_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
