# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20170702_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mainProject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='blogEntry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.BlogEntry'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='buildSteep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.BuildSteep'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='url'),
        ),
    ]
