# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20170702_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='projects/generated'),
        ),
    ]
