# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_resource_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='blogEntry',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='brief',
        ),
        migrations.AddField(
            model_name='blogentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/blog/'),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='title',
            field=models.CharField(default='Title', max_length=128, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='buildSteep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.BuildSteep'),
            preserve_default=False,
        ),
    ]
