# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20170716_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default=1, upload_to='projects/organization/'),
            preserve_default=False,
        ),
    ]
