# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 13:42
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20170720_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='description'),
        ),
    ]
