# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 16:01
from __future__ import unicode_literals

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20170720_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
    ]
