# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_organization_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='geolocation',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='google maps string'),
        ),
    ]
